### ISSUE TITLE
debugbarselector callback

### ISSUE THREAD

**Issue by forceedge01** [forceedge01/behat-fail-aid#43]
debugBarSelector only provides a way to read text from element, if the data is table set such as xhr request with url status code and response time it can be a difficult to read it all. Provide a callback feature:

Keep existing feature as is, but you can specific the following:
```
debugBarSelectors:
  xhrRequests:
    callback: class::method
    selector: string
```

Pass the retrieved element into the static method for further processing, the returned response is used in the failure text.
