### ISSUE TITLE
How to configure screenshots?

### ISSUE THREAD

**Issue by ptmkenny** [forceedge01/behat-fail-aid#71]
What is the issue?

I'm having trouble configuring screenshots.

The readme on the project page documents the configuration like this:
```

#behat.yml
...
- FailAid\Extension:
    screenshot:
        directory: /temp/failures/behat/screenshots/
        mode: default
        autoClean: false
        size: 1444x1280
        hostDirectory: /tmp/$USER/failures/
        hostUrl: http://ci/failures/$BRANCH_NAME/$JOB_NUMBER/failures/
```

So, I copied this into my `behat.yml`, changing the `directory` to `/app/web/files`, which I know behat can write to because I have other code that writes to that directory.

Next, I put `- FailAid\Extension:` at the root indentation level (the same level as `default:`.  This didn't work, and I got the following error:

`  You cannot define a sequence item when in a mapping at line 88 (near "- FailAid\Extension:").  
`

Next, I tried removing the `- ` and using `FailAid\Extension:` at the root indentation level (the same as `default`).  I did not get an error, but the screenshots were still saved to `/tmp`, not `/app/web/files`.

Next, I tried adding the config info under default extensions like this:

```
default:
  extensions:
    FailAid\Extension:
      output:
        screenshot:
          directory: /app/web/files
```

This gave another error about expecting a boolean and getting an array.

So where do I need to put the screenshot configuration in `behat.yml` to get it picked up correctly?
