### ISSUE TITLE
Ability to clean old screenshots

### ISSUE THREAD

**Issue by davidferlay** [forceedge01/behat-fail-aid#8]
### Action

1. Update behat.yml with 
```    FailAid\Extension:
      screenshotDirectory: /var/www/html/features/
      screenshotMode: default
```
_features directory being the one containing .feature files_

2. Prepare a scenario which will fail
3. Run behat
4. Scenario fails : behat-fail-aid will create html or png files as expected
5. Rerun behat

### Observed result

- html and png files of failing step will stack up in dir

### Expected result

- html and png files of failing step could be cleaned at fail before new ones are recreated
- such behavior could be defined in behat.yml config : 
```    FailAid\Extension:
      screenshotDirectory: /var/www/html/features/
      screenshotMode: default
      screenshotClean: true
```

### Todo

* Discuss relavancy
* Implement feature

**Comment by forceedge01** [comment]
Thanks for logging the issue @davidferlay , I agree it would be useful to have this feature. I will try and implement something along these lines as an option in the behat.yml file as it can be useful to retain screenshots while going through a debugging spree.

**Comment by forceedge01** [comment]
Merged https://github.com/forceedge01/behat-fail-aid/pull/9 and readme updated on usage. Please install v2.1.0 for feature.

**Comment by davidferlay** [comment]
> Merged #9 and readme updated on usage. Please install v2.1.0 for feature.

Thanks for such quick work) autoClean works great but i now encounter a strange issue : 

- I ran `composer update genesis/behat-fail-aid` and update my behat.yml file as bellow

- For some reason however, behat now expects my behat.yml file to be in my /web directory
Whereas in the past, it has been in it's parent directory and working fine : 

![2019-06-10_20-24](https://user-images.githubusercontent.com/20738264/59217369-12627400-8bbe-11e9-9470-385fcc0f932b.png)


behat.yml : 
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - FailAid\Context\FailureContext
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
      base_url: URL_TO_TEST # Will be replaced automatically by running "make behat" command
      sessions:
        default:
          chrome:
            api_url: http://0.0.0.0:9222
            validate_certificate: false
      # goutte: ~
      # selenium2: ~
    FailAid\Extension:
      screenshot:
        directory: /var/www/html/features/
        mode: default
        autoClean: true
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: 'web'
```

As you can see, i'm using behat-fail-aid alongside DrupalExtension where "web" dir is defined but had no impact on your extension previous to the update

Any clue what's happening ? )
